apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: ajju121/python-devops-demo:latest  # Aapki DockerHub image
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # Health Check logic (Jo humne pehle discuss kiya tha)
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
